### ISSUE TITLE
    implementation 'com.lonelypluto:pdf-viewer:1.0.7'

### ISSUE THREAD

**Issue by keaitao0321** [LonelyPluto/PdfViewerDemo#11]
implementation 'com.lonelypluto:pdf-viewer:1.0.7'

**Comment by keaitao0321** [comment]
这个的源码哪里有,我要修改下.批注划线的内容要读取出来,另外一个列表展示

**Comment by LonelyPluto** [comment]
@keaitao0321 源码请参考mupdf，自行编译

**Comment by keaitao0321** [comment]
我参照的是这个 https://github.com/viavansi/mupdf-android
但是发现很多api改了,能提供下么.

**Comment by LonelyPluto** [comment]
@keaitao0321 https://mupdf.com/downloads/

**Comment by keaitao0321** [comment]
请教划线的文本和位置有办法获取到么

**Comment by LonelyPluto** [comment]
@keaitao0321 暂时没有考虑这个问题
