### ISSUE TITLE
couldn't find "libmupdf_java.so"

### ISSUE THREAD

**Issue by 252162875** [LonelyPluto/PdfViewerDemo#12]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lonelypluto.pdfviewerdemo-NESEBDxYYHYT985OnRiwkA==/base.apk"],nativeLibraryDirectories=[/data/app/com.lonelypluto.pdfviewerdemo-NESEBDxYYHYT985OnRiwkA==/lib/arm64, /system/lib64]]] couldn't find "libmupdf_java.so"

**Comment by Alwaysm** [comment]
遇到同样的问题，解决了吗？

**Comment by lfclfc** [comment]
+1

**Comment by oy-paddy** [comment]
@lfclfc @Alwaysm @252162875 
你要看看除了armeabi-v7a和x86 库文件，是否还有其他的库文件（如arm64_v8之类的）。则arm64_v8也要放入对应的文件，否则会找不到库文件，因为你的设备如果是arm64_v8 的，会优先从arm64_v8 查找，没有这个库文件夹才会继续往下。
最好统一库文件，每个库文件的文件要统一

**Comment by LonelyPluto** [comment]
@252162875 @Alwaysm @lfclfc 目前只支持两种ABI：armeabi-v7a和x86，并不支持arm64

**Comment by zhangzhichao1992** [comment]
下载的代码可以运行，导入1.0.7这个库报错couldn't find "libmupdf_java.so"，请问这是什么原因？
