### ISSUE TITLE
大佬so文件能给一下吗

### ISSUE THREAD

**Issue by jiangwenfei** [LonelyPluto/PdfViewerDemo#14]

**Comment by lfclfc** [comment]
+1

**Comment by LonelyPluto** [comment]
@jiangwenfei @lfclfc 邮箱发一下

**Comment by jiangwenfei** [comment]
wenfeijiang0738@163.com  谢谢啦

**Comment by LonelyPluto** [comment]
@jiangwenfei 已发

**Comment by zhangzhichao1992** [comment]
大佬，so文件也给我发一份可以吗？谢谢啦，zhichao_2010@126.com

**Comment by LonelyPluto** [comment]
so文件已分享到github项目中，请自行下载&nbsp;




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shmily"<notifications@github.com&gt;; 
发送时间: 2021年1月17日(星期天) 晚上7:39
收件人: "LonelyPluto/PdfViewerDemo"<PdfViewerDemo@noreply.github.com&gt;; 
抄送: "窵傂諵"<277857006@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [LonelyPluto/PdfViewerDemo] 大佬so文件能给一下吗 (#14)





 
大佬，so文件也给我发一份可以吗？谢谢啦，zhichao_2010@126.com
