### ISSUE TITLE
添加批注后保存，笔迹变粗

### ISSUE THREAD

**Issue by sunchangdong** [LonelyPluto/PdfViewerDemo#2]
首先感谢你提供了这个公开库，正发愁不知道怎么使用mupdf呢。现在使用了最新的1.0.6版本，发现在进行添加批注的时候，在正常展示和放大展示两种状态下，画笔的粗细设置一样，但是将批注保存后，显示的批注粗细不一样。
经过检查发现是由于你在pageview类中的569行进行了放大处理，在保存的时候造成笔迹变粗，我在自己保存的地方根据缩放倍数进行了相除，保存变得正常

**Comment by LonelyPluto** [comment]
@sunchangdong 非常感谢你提供的bug，我已经做了修改，库已经更新
