### ISSUE TITLE
怎样把批注后的文件保存到本地

### ISSUE THREAD

**Issue by luenghw** [LonelyPluto/PdfViewerDemo#3]

**Comment by LonelyPluto** [comment]
@luenghw 当文档批注后，退出时会提示是否保存，点“是”就会将批注后的文件保存了

**Comment by luenghw** [comment]
> @luenghw 当文档批注后，退出时会提示是否保存，点“是”就会将批注后的文件保存了

貌似不知道保存到什么地方了，是原文件还是保存到另外的文件

**Comment by LonelyPluto** [comment]
@luenghw 是直接在原文件上保存的
