### ISSUE TITLE
请问一下,按照你这种依赖的形式,运行提示couldn't find "libmupdf_java.so"是怎么回事?

### ISSUE THREAD

**Issue by roybill** [LonelyPluto/PdfViewerDemo#6]
该怎么解决呢?

**Comment by LonelyPluto** [comment]
@roybill 可能没有你手机CPU类型的so文件，目前支持的CPU类型只有armeabi-v7a和x86两种，看下你手机的CPU类型是哪种

**Comment by roybill** [comment]
@LonelyPluto  我在gradle内这样配置是可以运行了，但是打开后只展示PDF文件，没有任何其他签名之类的操作，这是怎么回事呢？
 ndk {
            abiFilters 'armeabi', 'armeabi-v7a' , 'arm64-v8a'
        }

**Comment by LonelyPluto** [comment]
@roybill 请下载demo查看具体操作

**Comment by sunchangdong** [comment]
关于提示couldn't find "libmupdf_java.so"，我最近测试发现只有在gradle版本为3.2.1的时候不会出现，在其他版本的gradle都会出现这个错误。只要改换两个地方：1、项目的buiid.gradle文件里面的classpath 'com.android.tools.build:gradle:3.2.1'，2、gradle-wrapper.properties文件里面distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
